import { MenuItem } from './ui.service';

// export const MENU_ITEMS: MenuItem[] = [
//   {
//     category: 'burgers',
//     title: 'Classic Smash Burger',
//     image: 'img/menu/1.jpg',
//     price: '$14.99',
//     oldPrice: '$18.99',
//     rating: 4.9,
//     reviews: 128,
//     calories: 620,
//     prepTime: 12,
//     description:
//       'Double smashed patty, cheddar cheese, caramelized onions, house pickles and our legendary special sauce. Made fresh to order on a toasted brioche bun.',
//     tags: ['Spicy', 'Bestseller', 'Beef'],
//     badge: { text: 'Hot', type: 'hot' },
//   },
//   {
//     category: 'pizza',
//     title: 'Margherita Royale',
//     image: 'img/menu/2.jpg',
//     price: '$19.99',
//     oldPrice: '$24.99',
//     rating: 4.8,
//     reviews: 95,
//     calories: 480,
//     prepTime: 18,
//     description:
//       'San Marzano tomatoes, fresh buffalo mozzarella, fragrant basil leaves, drizzled with Italian truffle oil on a hand-stretched sourdough base.',
//     tags: ['Vegetarian', 'New', 'Italian'],
//     badge: { text: 'New', type: 'new' },
//   },
//   {
//     category: 'chicken',
//     title: 'Nashville Hot Chicken',
//     image: 'img/menu/3.jpg',
//     price: '$12.99',
//     oldPrice: '$16.99',
//     rating: 5.0,
//     reviews: 210,
//     calories: 710,
//     prepTime: 15,
//     description:
//       'Extra-crispy fried chicken tossed in our signature fiery Nashville spice blend, served with honey drizzle and house pickles on a toasted brioche bun.',
//     tags: ['Spicy', 'Bestseller', 'Crispy'],
//     badge: { text: 'Best Seller' },
//   },
//   {
//     category: 'wraps',
//     title: 'Loaded Fajita Wrap',
//     image: 'img/menu/4.jpg',
//     price: '$10.99',
//     rating: 4.5,
//     reviews: 74,
//     calories: 520,
//     prepTime: 10,
//     description:
//       'Grilled chicken strips, saut\u00e9ed bell peppers and onions, sour cream, fresh guacamole and salsa wrapped in a warm flour tortilla with melted cheddar.',
//     tags: ['Grilled', 'Fresh', 'Mexican'],
//   },
//   {
//     category: 'desserts',
//     title: 'Nutella Lava Cake',
//     image: 'img/menu/5.jpg',
//     price: '$8.99',
//     oldPrice: '$11.99',
//     rating: 4.9,
//     reviews: 56,
//     calories: 390,
//     prepTime: 8,
//     description:
//       'Warm molten chocolate cake with a gooey Nutella center, served alongside Madagascar vanilla bean ice cream with salted caramel drizzle and fresh berries.',
//     tags: ['Sweet', 'New', 'Chocolate'],
//     badge: { text: 'New', type: 'new' },
//   },
//   {
//     category: 'pasta',
//     title: 'Truffle Mushroom Pasta',
//     image: 'img/menu/6.jpg',
//     price: '$16.99',
//     rating: 4.9,
//     reviews: 88,
//     calories: 560,
//     prepTime: 20,
//     description:
//       'Al dente tagliatelle tossed with mixed wild mushrooms, freshly shaved black truffle, aged parmesan, fresh thyme and a touch of cream in garlic butter.',
//     tags: ["Vegetarian", "Chef's Pick", 'Italian'],
//     badge: { text: "Chef's Pick", type: 'hot' },
//   },
// ];
